server:
  port: 9002
  servlet:
    context-path: /res/v1
spring:
  application:
    name: restaurant-order
  datasource:
    url: jdbc:h2:mem:restaurant
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

