server:
  port: 9002
spring:
  application:
    name: Order Service
  datasource:
    url: jdbc:h2:mem:restaurant
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate: INFO

